language: java
jdk: oraclejdk11
services:
- docker
install: true
script:
- if [[ $TRAVIS_COMMIT_MESSAGE != 'SNAPSHOT UPDATE' ]]; then ./gradlew build
  --info; fi
branches:
  only:
  - master
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- |
  set -e
  if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ $TRAVIS_COMMIT_MESSAGE != "SNAPSHOT UPDATE" ]]; then
    echo "$DOCKER_PASSWORD" | base64 --decode | docker login "$DOCKER_REGISTRY" --username "$DOCKER_USERNAME" --password-stdin
    docker build -t "$DOCKER_LOCATION"/census-rm-fwmttmmock -t "$DOCKER_LOCATION"/census-rm-fwmttmmock:mock-service-$TRAVIS_BUILD_NUMBER --build-arg jar=build/libs/census-fwmt-tm-mock-*.jar .;
    docker push "$DOCKER_LOCATION"/census-rm-fwmttmmock;
  fi
- |
  set -e
  if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ $TRAVIS_COMMIT_MESSAGE != "SNAPSHOT UPDATE" ]]; then
    ./gradlew artifactPublish
  fi
- |
  set -e
  if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ $TRAVIS_COMMIT_MESSAGE != "SNAPSHOT UPDATE" ]]; then
    git config --global user.email "$EMAIL"
    git config --global user.name "$UNAME"
    git checkout master
    num=$(($(grep "version = .*\-SNAPSHOT" build.gradle | sed -e 's/^.*\.\([0-9]*\)-.*$/\1/')+1))
    sed -ie "s/\(^version.*[0-9]*\.[0-9]*\.\)[0-9]*/\1${num}/" build.gradle
    git add build.gradle
    git commit -m "SNAPSHOT UPDATE"
    git push https://$UNAME:$PASSWD@$REPO
  fi