language: java
jdk: openjdk11
services:
- docker
before_install:
  - docker run -d --name rabbit -p 5672:5672 rabbitmq:3.6
  - echo "artifactory_user=${ARTIFACTORY_USERNAME}" >> ~/.gradle/gradle.properties
  - echo "artifactory_password=${ARTIFACTORY_PASSWORD}" >> ~/.gradle/gradle.properties
install: true
script:
  if [[ $TRAVIS_COMMIT_MESSAGE != 'SNAPSHOT UPDATE' ]]; then
      ./gradlew build  --info --refresh-dependencies ;
  fi
branches:
  only:
  - master
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
