server:
  port: 9099
  servlet:
    context-path: /

spring:
  application:
    name: fwmt-census-tm-mocks
  security:
    user:
      name: "user"
      password: "password"
  jackson:
    date-format: uk.gov.ons.fwmt.census.tm.mock.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springfox.documentation.swagger.v2.path: "/api-docs"

# Place /info and /health in the root
management.endpoints.web.base-path: ''

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"

totalmobile:
  username: ""
  password: ""
  url: ""
  message-queue-path: "/ws/MessageQueueWs.asmx"
  message-queue-wsdl-path: "src/main/resources/wsdl/Messaging_MessageQueueWs.wsdl"
  message-queue-namespace: "http://schemas.consiliumtechnologies.com/wsdl/mobile/2007/07/messaging/"
  message-queue-package: "com.consiliumtechnologies.schemas.services.mobile._2009._03.messaging"
  outgoing-ws-namespace: "http://schemas.consiliumtechnologies.com/services/mobile/2009/03/messaging"
  web:
    login-url: "/WebAdmin/Login"
    save-user-url: "/WebAdmin/Administration/Users/SaveUser"

rabbitmq:
  rm:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtualHost: /
  fwmt:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtualHost: /

customisation:
  logging:
    logFlagType: "logAllMessages"