/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package uk.gov.ons.fwmt.service_mocks.comet.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import uk.gov.ons.fwmt.service_mocks.comet.model.Body;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-21T14:54:52.766Z")
@Api(value = "cases", description = "the cases API")
public interface CasesApi {

  @ApiOperation(value = "Get Cases", nickname = "5bbb3cadf29b98bb78799f97", notes = "Gets the list of cases that match the specified criteria", authorizations = {
      @Authorization(value = "apiKeyHeader"),
      @Authorization(value = "apiKeyQuery"),
      @Authorization(value = "oauth2ons-dev-web-app-oauth2-service", scopes = {

      })
  }, tags = {"Cases",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "The cases that match the specified criteria")})
  @RequestMapping(value = "/cases",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<Void> getCases(
      @ApiParam(value = "Specifies the filters to be applied to the search") @Valid @RequestParam(value = "filter", required = false) String filter,
      @ApiParam(value = "The page to be returned.") @Valid @RequestParam(value = "pageNo", required = false) Integer pageNo,
      @ApiParam(value = "The size of the page to be returned") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize);

  @ApiOperation(value = "Create or Amend Case", nickname = "createOrAmendCase", notes = "Creates or amends the case identified by the id.", authorizations = {
      @Authorization(value = "apiKeyHeader"),
      @Authorization(value = "apiKeyQuery"),
      @Authorization(value = "oauth2ons-dev-web-app-oauth2-service", scopes = {

      })
  }, tags = {"Cases",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "The specified case was successfully updated"),
      @ApiResponse(code = 201, message = "A new case was created with the specified id")})
  @RequestMapping(value = "/cases/{id}",
      produces = {"application/json"},
      consumes = {"application/json"},
      method = RequestMethod.PUT)
  ResponseEntity<Void> createOrAmendCase(
      @ApiParam(value = "The case id", required = true) @PathVariable("id") String id,
      @ApiParam(value = "") @Valid @RequestBody Body body);

  @ApiOperation(value = "Get Case", nickname = "getCase", notes = "Gets a case identified by its case id", authorizations = {
      @Authorization(value = "apiKeyHeader"),
      @Authorization(value = "apiKeyQuery"),
      @Authorization(value = "oauth2ons-dev-web-app-oauth2-service", scopes = {

      })
  }, tags = {"Cases",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "The case identified by the id"),
      @ApiResponse(code = 404, message = "The requested case does not exist")})
  @RequestMapping(value = "/cases/{id}",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<Void> getCase(@ApiParam(value = "The case identifier", required = true) @PathVariable("id") String id);

}
