/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package uk.gov.ons.fwmt.service_mocks.comet.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-21T14:54:52.766Z")
@Api(value = "scheduled-jobs", description = "the scheduled-jobs API")
public interface ScheduledJobsApi {

  @ApiOperation(value = "Get Scheduled Jobs", nickname = "getScheduledJobs", notes = "Gets all scheduled jobs for the specified officer", authorizations = {
      @Authorization(value = "apiKeyHeader"),
      @Authorization(value = "apiKeyQuery"),
      @Authorization(value = "oauth2ons-dev-web-app-oauth2-service", scopes = {

      })
  }, tags = {"Scheduled Jobs",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "The scheduled jobs for the given officer")})
  @RequestMapping(value = "/scheduled-jobs/{officerId}",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<Void> getScheduledJobs(
      @ApiParam(value = "Officer ID to query scheduled jobs for", required = true) @PathVariable("officerId") String officerId);

}
