/*
 * Census Operations Mobile Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package comet.client.api;

import org.junit.Ignore;
import org.junit.Test;
import uk.gov.ons.fwmt.service_mocks.comet.client.api.CasesApi;
import uk.gov.ons.fwmt.service_mocks.comet.client.model.Body;

/**
 * API tests for CasesApi
 */
@Ignore
public class CasesApiTest {

  private final CasesApi api = new CasesApi();

  /**
   * Get Cases
   * <p>
   * Gets the list of cases that match the specified criteria
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getCasesTest() {
    String filter = null;
    Integer pageNo = null;
    Integer pageSize = null;
    api.getCase(filter, pageNo, pageSize);

    // TODO: test validations
  }

  /**
   * Create or Amend Case
   * <p>
   * Creates or amends the case identified by the id.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void createOrAmendCaseTest() {
    String id = null;
    Body body = null;
    api.createOrAmendCase(id, body);

    // TODO: test validations
  }

  /**
   * Get Case
   * <p>
   * Gets a case identified by its case id
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getCaseTest() {
    String id = null;
    api.getCase(id);

    // TODO: test validations
  }

}
