/*
 * Census Operations Mobile Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package comet.client.api;

import org.junit.Ignore;
import org.junit.Test;
import uk.gov.ons.fwmt.service_mocks.comet.client.api.DefaultApi;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

  private final DefaultApi api = new DefaultApi();

  /**
   * Get Officer Availability
   * <p>
   * Gets the roster for the currently logged in co-ordinator
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void rosterTest() {
    String startDate = null;
    String endDate = null;
    api.roster(startDate, endDate);

    // TODO: test validations
  }

}
