/*
 * Census Operations Mobile Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package comet.client.api;

import org.junit.Ignore;
import org.junit.Test;
import uk.gov.ons.fwmt.service_mocks.comet.client.api.OfficersApi;
import uk.gov.ons.fwmt.service_mocks.comet.client.model.Body;

/**
 * API tests for OfficersApi
 */
@Ignore
public class OfficersApiTest {

  private final OfficersApi api = new OfficersApi();

  /**
   * Create or Amend Officer
   * <p>
   * Create or Amend Officer
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void createOrAmendOfficerTest() {
    String id = null;
    Body body = null;
    api.createOrAmendOfficer(id, body);

    // TODO: test validations
  }

  /**
   * Get Officer
   * <p>
   * Gets an officer identified by the supplied ID
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getOfficerTest() {
    String id = null;
    api.getOfficer(id);

    // TODO: test validations
  }

  /**
   * Get Officers
   * <p>
   * Get Officers
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getOfficersTest() {
    String filter = null;
    Integer pageNo = null;
    Integer pageSize = null;
    api.getOfficers(filter, pageNo, pageSize);

    // TODO: test validations
  }

}
